### ISSUE TITLE
[CDS-Toolkit][ConsentMgr] - admin user unable to see the consent amendment history of a business consent

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#184]
**Description:**
"Failed to fetch consent history data, Try again later" error in consent amendment history tab for admin user. In here the consent is created and amended by "nominatedUser1@wso2.com".

<img width="1720" alt="Screenshot 2024-11-06 at 3 42 58 PM" src="https://github.com/user-attachments/assets/6f0dea08-1e11-45e0-9512-0a3eeedbe882">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Create and Amend business user consent.
2. Log into consent manager portal via admin credentials.
3. Verify the consent amendment history.

**Related Issues:**

**Comment by anjuchamantha** [comment]
The expected behaviour is we show the consent amendment history only to the primary members [1] or to the customer care officer [2]. In this case since the admin is not a primary member, we don't show history.

[1] https://github.com/wso2/reference-implementation-consumerdatastandards-au/blob/1a74c69596495070a6f5015e0cc47fbe617d9713/components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/admin/impl/CDSConsentAdminHandler.java#L181

[2] Adds in a future fix...

**Comment by malshaniS** [comment]
Closing the issue based on the above comment
